#!/usr/bin/env bash
# --- Guard ---
[[ -n "${_DOCKER_LOGIC_SH_SOURCED:-}" ]] && return 0
_DOCKER_LOGIC_SH_SOURCED=1

# --- Strict Mode ---
set -Eeuo pipefail

# --- Constants ---
readonly COMPOSE_TARGET="${INSTALLER_DIR:-.}/docker-compose.yml"
readonly TEMPLATES_DIR="${INSTALLER_DIR:-.}/templates"
readonly HEALTH_TIMEOUT_VAL="${HEALTH_TIMEOUT:-120}"

# --- Dependencies ---
# Depends on state-manager.sh for safe_write_env
# shellcheck disable=SC1091
if [[ -f "${BATS_TEST_DIRNAME:-.}/../lib/state-manager.sh" ]]; then
    source "${BATS_TEST_DIRNAME:-.}/../lib/state-manager.sh"
elif [[ -f "${INSTALLER_DIR:-.}/lib/state-manager.sh" ]]; then
    source "${INSTALLER_DIR:-.}/lib/state-manager.sh"
fi

# --- Decoder configuration ---
get_ultrafeeder_config() {
    local config=""
    
    # Modern Aggregators (Internal to ultrafeeder v3)
    if [[ "${ENABLE_AGGREGATORS:-true}" == "true" ]]; then
        # ADSB.fi
        config+="adsb,feed.adsb.fi,30004,beast_reduce_plus_out;mlat,feed.adsb.fi,31090;"
        # ADSB.lol
        config+="adsb,in.adsb.lol,30004,beast_reduce_plus_out;mlat,in.adsb.lol,31090;"
        # Airplanes.live
        config+="adsb,feed.airplanes.live,30004,beast_reduce_plus_out;mlat,feed.airplanes.live,31090;"
        # Planespotters.net
        config+="adsb,feed.planespotters.net,30004,beast_reduce_plus_out;mlat,mlat.planespotters.net,31090;"
        # TheAirTraffic.com
        config+="adsb,feed.theairtraffic.com,30004,beast_reduce_plus_out;mlat,feed.theairtraffic.com,31090;"
        # AvDelphi
        config+="adsb,data.avdelphi.com,24999,beast_reduce_plus_out;"
        # HPRadar
        config+="adsb,skyfeed.hpradar.com,30004,beast_reduce_plus_out;mlat,skyfeed.hpradar.com,31090;"
        # FlyItalyADSB
        config+="adsb,dati.flyitalyadsb.com,4905,beast_reduce_plus_out;mlat,dati.flyitalyadsb.com,30100;"
        # ADSBExchange
        config+="adsb,feed1.adsbexchange.com,30004,beast_reduce_plus_out;mlat,feed.adsbexchange.com,31090;"
    fi

    # Sidecar Feeders requiring specific ultrafeeder inputs
    if [[ "${ENABLE_PLANEWATCH:-false}" == "true" ]]; then
        # Plane-Watch MLAT results
        config+="mlat,planewatch,30105;"
    fi

    # UAT (dump978) Integration
    if [[ "${ENABLE_UAT:-false}" == "true" ]]; then
        # Pull demodulated UAT data from dump978 container
        config+="adsb,dump978,30978;"
    fi
    
    echo "$config"
}

# --- Template Merging ---
assemble_compose() {
    # Ensure environment is prepared
    prepare_deployment_env || return 20
    
    # Build ULTRAFEEDER_CONFIG for templates
    local uf_config
    uf_config=$(get_ultrafeeder_config)
    safe_write_env "ULTRAFEEDER_CONFIG" "$uf_config"
    export ULTRAFEEDER_CONFIG="$uf_config"
    
    info "Assembling modular docker-compose.yml..."
    
    local target_file="$COMPOSE_TARGET"
    local compose_dir="${INSTALLER_DIR:-.}/compose"
    
    # Ensure compose directory exists and is clean
    mkdir -p "$compose_dir"
    rm -f "${compose_dir}"/*.yml
    
    local -a include_paths=()
    
    # 1. Base (ultrafeeder)
    if [[ -f "${TEMPLATES_DIR}/base.yml" ]]; then
        cp "${TEMPLATES_DIR}/base.yml" "${compose_dir}/ultrafeeder.yml"
        include_paths+=("compose/ultrafeeder.yml")
    else
        error "Missing base template at ${TEMPLATES_DIR}/base.yml"
        return 20
    fi
    
    # 2. Conditional Feeders (External sidecars)
    local -a feeders=(fa fr24 planewatch rbfeeder pfclient adsbhub opensky radarvirtuel)
    for feeder in "${feeders[@]}"; do
        local var_name="ENABLE_${feeder^^}"
        if [[ "${!var_name:-false}" == "true" ]]; then
            if [[ -f "${TEMPLATES_DIR}/${feeder}.yml" ]]; then
                cp "${TEMPLATES_DIR}/${feeder}.yml" "${compose_dir}/${feeder}.yml"
                include_paths+=("compose/${feeder}.yml")
            else
                warn "Enabled feeder template missing: ${TEMPLATES_DIR}/${feeder}.yml"
            fi
        fi
    done

    # 3. Optional UAT (978MHz) Suite
    if [[ "${ENABLE_UAT:-false}" == "true" ]]; then
        if [[ -f "${TEMPLATES_DIR}/uat.yml" ]]; then
            cp "${TEMPLATES_DIR}/uat.yml" "${compose_dir}/uat.yml"
            include_paths+=("compose/uat.yml")
        fi
    fi

    # 4. Optional Visualizer Suite
    if [[ "${ENABLE_GRAPHS:-false}" == "true" ]]; then
        if [[ -f "${TEMPLATES_DIR}/graphs.yml" ]]; then
            cp "${TEMPLATES_DIR}/graphs.yml" "${compose_dir}/graphs.yml"
            include_paths+=("compose/graphs.yml")
        fi
    fi

    # 4. Generate Master Compose File
    local temp_file="${target_file}.tmp"
    cat <<EOF > "$temp_file"
# Master ADS-B Docker Compose File
# Generated by ADS-B Installer

include:
EOF

    for path in "${include_paths[@]}"; do
        echo "  - path: $path" >> "$temp_file"
    done

    # 5. Networks (Defined at master level)
    if [[ -f "${TEMPLATES_DIR}/networks.yml" ]]; then
        echo "" >> "$temp_file"
        cat "${TEMPLATES_DIR}/networks.yml" >> "$temp_file"
    fi
    
    mv "$temp_file" "$target_file"
    info "Generated modular $target_file"
}

# --- Environment Prep ---
prepare_deployment_env() {
    info "Preparing project environment..."
    
    local target_dir="${INSTALLER_DIR:-.}"
    
    # Target directory check
    if [[ ! -d "$target_dir" ]]; then
        mkdir -p "$target_dir" || {
            error "Failed to create project directory: $target_dir"
            return 20
        }
    fi
    
    # Handle volumes (SDR-Enthusiasts pattern)
    mkdir -p "${target_dir}/volumes/ultrafeeder/globe_history"
    mkdir -p "${target_dir}/volumes/ultrafeeder/graphs1090"
    
    # Network pre-creation
    if ! docker network ls | grep -q " adsb "; then
        info "Creating Docker network: adsb"
        docker network create adsb &>/dev/null || true
    fi
    
    # UUID Generation if missing from environment
    if [[ -z "${STATION_UUID:-}" ]]; then
        if [[ -f "/proc/sys/kernel/random/uuid" ]]; then
            local uuid
            uuid=$(cat /proc/sys/kernel/random/uuid)
            export STATION_UUID="$uuid"
            safe_write_env "STATION_UUID" "$STATION_UUID"
            info "Generated and persisted Station UUID: $STATION_UUID"
        fi
    fi
    
    return 0
}

# --- Compose Wrapper ---
is_stack_deployed() {
    local compose_cmd
    compose_cmd=$(get_compose_cmd)
    
    # Check if a container with the ultrafeeder name exists and is managed by this project
    if docker ps -a --format '{{.Names}}' | grep -q "ultrafeeder"; then
        return 0
    fi
    return 1
}

get_compose_cmd() {
    if docker compose version &>/dev/null; then
        echo "docker compose"
    elif command -v docker-compose &>/dev/null; then
        # Warning for modern Docker vs Compose V1
        local d_ver
        d_ver=$(docker version --format '{{.Server.Version}}' 2>/dev/null | cut -d. -f1)
        if [[ "$d_ver" =~ ^[0-9]+$ ]] && (( d_ver >= 25 )); then
            warn "Detected Docker v${d_ver} with legacy docker-compose (v1)."
            warn "This combination is known to cause 'KeyError: ContainerConfig'."
            warn "Please install 'docker-compose-v2' (apt) or 'docker-compose-plugin'."
        fi
        echo "docker-compose"
    else
        # Fallback to the one we hope to find or just fail gracefully later
        echo "docker compose"
    fi
}

# --- Deployment ---
deploy_stack() {
    local compose_cmd
    compose_cmd=$(get_compose_cmd)
    
    info "Deploying ADS-B stack..."
    
    # Atomic assembly
    assemble_compose || return 20
    
    # Pre-flight: verify volumes
    mkdir -p "${INSTALLER_DIR:-.}/volumes"
    
    if [[ "${_ADSB_DRY_RUN:-false}" == "true" ]]; then
        info "[DRY RUN] Would execute: $compose_cmd pull && $compose_cmd up -d --remove-orphans"
        return 0
    fi
    
    if ! $compose_cmd pull; then
        error "$compose_cmd pull failed"
        return 20
    fi
    
    if ! $compose_cmd up -d --remove-orphans; then
        error "$compose_cmd up failed"
        return 20
    fi
    
    verify_deployment
}

# --- Health Check ---
verify_deployment() {
    info "Verifying deployment health (Timeout: ${HEALTH_TIMEOUT_VAL}s)..."
    
    local elapsed=0
    local interval=5
    
    while (( elapsed < HEALTH_TIMEOUT_VAL )); do
        if check_health_once; then
            info "Stack is healthy!"
            return 0
        fi
        
        sleep "$interval"
        (( elapsed += interval ))
        info "Waiting for healthy state... (${elapsed}/${HEALTH_TIMEOUT_VAL}s)"
    done
    
    error "Health check timeout exceeded."
    return 20
}

check_health_once() {
    # Check if all containers are running/healthy
    local status
    local compose_cmd
    compose_cmd=$(get_compose_cmd)
    
    status=$($compose_cmd ps --format json 2>/dev/null || true)
    
    if [[ -z "$status" ]]; then return 1; fi
    
    # Simplistic check: if any are marked as "starting" or "exited", fail once
    if echo "$status" | grep -qvE "running|healthy"; then
        return 1
    fi
    
    # Optional: curl check
    if ! curl -Is localhost:8080 >/dev/null 2>&1; then
        return 1
    fi
    
    # Feeder log checks (Sidecars)
    if [[ "${ENABLE_FA:-false}" == "true" ]]; then
        if ! check_feeder_logs "piaware" "fa"; then
            info "Still waiting for FlightAware (piaware) to initialize..."
            return 1
        fi
    fi
    if [[ "${ENABLE_FR24:-false}" == "true" ]]; then
        if ! check_feeder_logs "fr24" "fr24"; then
            info "Still waiting for Flightradar24 (fr24) to initialize..."
            return 1
        fi
    fi
    
    # Internal Aggregators (ultrafeeder)
    if [[ "${ENABLE_AGGREGATORS:-true}" == "true" ]]; then
        # Informational check for a few key aggregators, but don't fail the loop
        local -a key_aggregators=(adsblol airplanes adsbexchange)
        for agg in "${key_aggregators[@]}"; do
            if ! check_feeder_logs "ultrafeeder" "$agg"; then
                info "Service Info: $agg is still connecting via ultrafeeder (informational)..."
            fi
        done
    fi
    
    return 0
}

check_feeder_logs() {
    local container_name="$1"
    local search_hint="${2:-$1}"
    local logs
    
    logs=$(docker logs "$container_name" 2>&1 | tail -n 50) || return 1
    
    # Connected patterns
    # 1. If we have a specific search_hint and the container is NOT the feeder itself (internal aggregator case)
    if [[ "$container_name" != "$search_hint" ]]; then
        if echo "$logs" | grep -qiE "(${search_hint}.*connected|${search_hint}.*success|Connected to [a-z0-9.]*${search_hint})"; then
            return 0
        fi
    else
        # 2. Sidecar case: patterns for specific feeders
        if [[ "$container_name" == "fr24" ]]; then
             if echo "$logs" | grep -qiE "(Connected to the receiver|processing messages|Feed Network client started)"; then
                return 0
             fi
        elif [[ "$container_name" == "piaware" ]]; then
             if echo "$logs" | grep -qiE "(Connected to localhost|Messages successfully uploaded|piaware version.*starting)"; then
                return 0
             fi
        fi

        # Generic fallback
        if echo "$logs" | grep -qiE "(Beast input connected|TCP connect success|Connected to [a-z0-9.]+|Startup.*success)"; then
            return 0
        fi
    fi
    
    # 3. Authentication/Key failure patterns
    # Added FR24 specific: "check your key!"
    if echo "$logs" | grep -iE "$search_hint" | grep -qiE "(Invalid key|Incorrect credentials|Authentication failed|check your key!)"; then
        error "Feeder $search_hint ($container_name): Authentication failed. Check your key."
        return 1
    fi
    
    # Still starting or no data yet
    return 1
}

# --- Stop ---
stop_stack() {
    local compose_cmd
    compose_cmd=$(get_compose_cmd)
    info "Stopping ADS-B stack..."
    $compose_cmd down --remove-orphans
}
