services:
  # Performance Graphs (tar1090)
  tar1090:
    image: mikenye/tar1090:latest
    container_name: tar1090
    restart: always
    environment:
      - TZ=${FEEDER_TZ:-UTC}
      - LAT=${LAT}
      - LON=${LON}
      - BEASTHOST=ultrafeeder
      - BEASTPORT=30005
    networks:
      - adsb
    ports:
      - 8081:80
    depends_on:
      - ultrafeeder
